// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsIu05t9Q9RP_XVG6o20CkpIodmz1o_JM',
    appId: '1:412363482923:web:b06259f7ea571820ec476e',
    messagingSenderId: '412363482923',
    projectId: 'syndic-f787f',
    authDomain: 'syndic-f787f.firebaseapp.com',
    storageBucket: 'syndic-f787f.firebasestorage.app',
    measurementId: 'G-PF5BNQ8W8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0GgbQlf_LO03UI5rchXyGTfDi324UBI',
    appId: '1:412363482923:android:3de713ff8038fd5eec476e',
    messagingSenderId: '412363482923',
    projectId: 'syndic-f787f',
    storageBucket: 'syndic-f787f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoFuBu4BMkBdNhJoLw2dZoxchh5OKFH6k',
    appId: '1:412363482923:ios:367f8e6a7a88d496ec476e',
    messagingSenderId: '412363482923',
    projectId: 'syndic-f787f',
    storageBucket: 'syndic-f787f.firebasestorage.app',
    iosBundleId: 'com.example.syndicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoFuBu4BMkBdNhJoLw2dZoxchh5OKFH6k',
    appId: '1:412363482923:ios:367f8e6a7a88d496ec476e',
    messagingSenderId: '412363482923',
    projectId: 'syndic-f787f',
    storageBucket: 'syndic-f787f.firebasestorage.app',
    iosBundleId: 'com.example.syndicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsIu05t9Q9RP_XVG6o20CkpIodmz1o_JM',
    appId: '1:412363482923:web:4b17240f7c2a1a56ec476e',
    messagingSenderId: '412363482923',
    projectId: 'syndic-f787f',
    authDomain: 'syndic-f787f.firebaseapp.com',
    storageBucket: 'syndic-f787f.firebasestorage.app',
    measurementId: 'G-S79NKPXRW5',
  );
}
